
package xmlweb.agent.soap.price;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PricePortService", targetNamespace = "http://xmlweb/projekat/entities/soap", wsdlLocation = "http://localhost:8089/booking/ws/price.wsdl")
public class PricePortService
    extends Service
{

    private final static URL PRICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRICEPORTSERVICE_EXCEPTION;
    private final static QName PRICEPORTSERVICE_QNAME = new QName("http://xmlweb/projekat/entities/soap", "PricePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/booking/ws/price.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRICEPORTSERVICE_WSDL_LOCATION = url;
        PRICEPORTSERVICE_EXCEPTION = e;
    }

    public PricePortService() {
        super(__getWsdlLocation(), PRICEPORTSERVICE_QNAME);
    }

    public PricePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRICEPORTSERVICE_QNAME, features);
    }

    public PricePortService(URL wsdlLocation) {
        super(wsdlLocation, PRICEPORTSERVICE_QNAME);
    }

    public PricePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRICEPORTSERVICE_QNAME, features);
    }

    public PricePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PricePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PricePort
     */
    @WebEndpoint(name = "PricePortSoap11")
    public PricePort getPricePortSoap11() {
        return super.getPort(new QName("http://xmlweb/projekat/entities/soap", "PricePortSoap11"), PricePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PricePort
     */
    @WebEndpoint(name = "PricePortSoap11")
    public PricePort getPricePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlweb/projekat/entities/soap", "PricePortSoap11"), PricePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRICEPORTSERVICE_EXCEPTION!= null) {
            throw PRICEPORTSERVICE_EXCEPTION;
        }
        return PRICEPORTSERVICE_WSDL_LOCATION;
    }

}
