
package xmlweb.agent.soap.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserPort", targetNamespace = "http://xmlweb/projekat/entities/soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserPort {


    /**
     * 
     * @param getUserRequest
     * @return
     *     returns xmlweb.agent.soap.user.GetUserResponse
     */
    @WebMethod
    @WebResult(name = "getUserResponse", targetNamespace = "http://xmlweb/projekat/soap/models", partName = "getUserResponse")
    public GetUserResponse getUser(
        @WebParam(name = "getUserRequest", targetNamespace = "http://xmlweb/projekat/soap/models", partName = "getUserRequest")
        GetUserRequest getUserRequest);

}
