//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 11:40:05 AM CEST 
//


package xmlweb.agent.soap.models.accomodation_bonus_service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accomodation_bonus_service_request" type="{http://xmlweb/projekat/soap/models/accomodation_bonus_service}AccomodationBonusServiceRequest" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accomodationBonusServiceRequest"
})
@XmlRootElement(name = "getAccomodationBonusServiceRequest")
public class GetAccomodationBonusServiceRequest {

    @XmlElement(name = "accomodation_bonus_service_request")
    protected List<AccomodationBonusServiceRequest> accomodationBonusServiceRequest;

    /**
     * Gets the value of the accomodationBonusServiceRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accomodationBonusServiceRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccomodationBonusServiceRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccomodationBonusServiceRequest }
     * 
     * 
     */
    public List<AccomodationBonusServiceRequest> getAccomodationBonusServiceRequest() {
        if (accomodationBonusServiceRequest == null) {
            accomodationBonusServiceRequest = new ArrayList<AccomodationBonusServiceRequest>();
        }
        return this.accomodationBonusServiceRequest;
    }

}
