
package xmlweb.agent.soap.picture;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PicturePortService", targetNamespace = "http://xmlweb/projekat/entities/soap", wsdlLocation = "http://localhost:8089/booking/ws/picture.wsdl")
public class PicturePortService
    extends Service
{

    private final static URL PICTUREPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PICTUREPORTSERVICE_EXCEPTION;
    private final static QName PICTUREPORTSERVICE_QNAME = new QName("http://xmlweb/projekat/entities/soap", "PicturePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/booking/ws/picture.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PICTUREPORTSERVICE_WSDL_LOCATION = url;
        PICTUREPORTSERVICE_EXCEPTION = e;
    }

    public PicturePortService() {
        super(__getWsdlLocation(), PICTUREPORTSERVICE_QNAME);
    }

    public PicturePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PICTUREPORTSERVICE_QNAME, features);
    }

    public PicturePortService(URL wsdlLocation) {
        super(wsdlLocation, PICTUREPORTSERVICE_QNAME);
    }

    public PicturePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PICTUREPORTSERVICE_QNAME, features);
    }

    public PicturePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PicturePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PicturePort
     */
    @WebEndpoint(name = "PicturePortSoap11")
    public PicturePort getPicturePortSoap11() {
        return super.getPort(new QName("http://xmlweb/projekat/entities/soap", "PicturePortSoap11"), PicturePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PicturePort
     */
    @WebEndpoint(name = "PicturePortSoap11")
    public PicturePort getPicturePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlweb/projekat/entities/soap", "PicturePortSoap11"), PicturePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PICTUREPORTSERVICE_EXCEPTION!= null) {
            throw PICTUREPORTSERVICE_EXCEPTION;
        }
        return PICTUREPORTSERVICE_WSDL_LOCATION;
    }

}
