
package xmlweb.agent.soap.message;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MessagePort", targetNamespace = "http://xmlweb/projekat/entities/soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MessagePort {


    /**
     * 
     * @param getMessageRequest
     * @return
     *     returns xmlweb.agent.soap.message.GetMessageResponse
     */
    @WebMethod
    @WebResult(name = "getMessageResponse", targetNamespace = "http://xmlweb/projekat/model/soap", partName = "getMessageResponse")
    public GetMessageResponse getMessage(
        @WebParam(name = "getMessageRequest", targetNamespace = "http://xmlweb/projekat/model/soap", partName = "getMessageRequest")
        GetMessageRequest getMessageRequest);

}
