
package xmlweb.agent.soap.message;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MessagePortService", targetNamespace = "http://xmlweb/projekat/entities/soap", wsdlLocation = "http://localhost:8089/booking/ws/message.wsdl")
public class MessagePortService
    extends Service
{

    private final static URL MESSAGEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSAGEPORTSERVICE_EXCEPTION;
    private final static QName MESSAGEPORTSERVICE_QNAME = new QName("http://xmlweb/projekat/entities/soap", "MessagePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/booking/ws/message.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSAGEPORTSERVICE_WSDL_LOCATION = url;
        MESSAGEPORTSERVICE_EXCEPTION = e;
    }

    public MessagePortService() {
        super(__getWsdlLocation(), MESSAGEPORTSERVICE_QNAME);
    }

    public MessagePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSAGEPORTSERVICE_QNAME, features);
    }

    public MessagePortService(URL wsdlLocation) {
        super(wsdlLocation, MESSAGEPORTSERVICE_QNAME);
    }

    public MessagePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSAGEPORTSERVICE_QNAME, features);
    }

    public MessagePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessagePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MessagePort
     */
    @WebEndpoint(name = "MessagePortSoap11")
    public MessagePort getMessagePortSoap11() {
        return super.getPort(new QName("http://xmlweb/projekat/entities/soap", "MessagePortSoap11"), MessagePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessagePort
     */
    @WebEndpoint(name = "MessagePortSoap11")
    public MessagePort getMessagePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlweb/projekat/entities/soap", "MessagePortSoap11"), MessagePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSAGEPORTSERVICE_EXCEPTION!= null) {
            throw MESSAGEPORTSERVICE_EXCEPTION;
        }
        return MESSAGEPORTSERVICE_WSDL_LOCATION;
    }

}
