//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 11:37:50 AM CEST 
//


package xmlweb.projekat.soap.services.send_message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="send_message" type="{http://xmlweb/projekat/soap/services/send_message}SendMessageSOAP"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendMessage"
})
@XmlRootElement(name = "getSendMessageResponse")
public class GetSendMessageResponse {

    @XmlElement(name = "send_message", required = true)
    protected SendMessageSOAP sendMessage;

    /**
     * Gets the value of the sendMessage property.
     * 
     * @return
     *     possible object is
     *     {@link SendMessageSOAP }
     *     
     */
    public SendMessageSOAP getSendMessage() {
        return sendMessage;
    }

    /**
     * Sets the value of the sendMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendMessageSOAP }
     *     
     */
    public void setSendMessage(SendMessageSOAP value) {
        this.sendMessage = value;
    }

}
