//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.24 at 09:55:26 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlweb/projekat/soap/models/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xmlweb.projekat.soap.models.user;
