//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 11:37:50 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlweb/projekat/soap/models/comment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xmlweb.projekat.soap.models.comment;
