//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.17 at 04:50:05 PM CEST 
//


package xmlweb.projekat.soap.models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlweb.projekat.soap.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlweb.projekat.soap.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAccomodationAgentResponse }
     * 
     */
    public GetAccomodationAgentResponse createGetAccomodationAgentResponse() {
        return new GetAccomodationAgentResponse();
    }

    /**
     * Create an instance of {@link AccomodationAgentSOAP }
     * 
     */
    public AccomodationAgentSOAP createAccomodationAgentSOAP() {
        return new AccomodationAgentSOAP();
    }

    /**
     * Create an instance of {@link GetAccomodationBonusRequest }
     * 
     */
    public GetAccomodationBonusRequest createGetAccomodationBonusRequest() {
        return new GetAccomodationBonusRequest();
    }

    /**
     * Create an instance of {@link AccomodationBonusServiceSOAP }
     * 
     */
    public AccomodationBonusServiceSOAP createAccomodationBonusServiceSOAP() {
        return new AccomodationBonusServiceSOAP();
    }

    /**
     * Create an instance of {@link GetAccomodationBonusResponse }
     * 
     */
    public GetAccomodationBonusResponse createGetAccomodationBonusResponse() {
        return new GetAccomodationBonusResponse();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link UserSOAP }
     * 
     */
    public UserSOAP createUserSOAP() {
        return new UserSOAP();
    }

    /**
     * Create an instance of {@link GetAccomodationTypeRequest }
     * 
     */
    public GetAccomodationTypeRequest createGetAccomodationTypeRequest() {
        return new GetAccomodationTypeRequest();
    }

    /**
     * Create an instance of {@link AccomodationTypeRequest }
     * 
     */
    public AccomodationTypeRequest createAccomodationTypeRequest() {
        return new AccomodationTypeRequest();
    }

    /**
     * Create an instance of {@link GetReservationRequest }
     * 
     */
    public GetReservationRequest createGetReservationRequest() {
        return new GetReservationRequest();
    }

    /**
     * Create an instance of {@link ReservationRequest }
     * 
     */
    public ReservationRequest createReservationRequest() {
        return new ReservationRequest();
    }

    /**
     * Create an instance of {@link GetCommentRequest }
     * 
     */
    public GetCommentRequest createGetCommentRequest() {
        return new GetCommentRequest();
    }

    /**
     * Create an instance of {@link CommentRequest }
     * 
     */
    public CommentRequest createCommentRequest() {
        return new CommentRequest();
    }

    /**
     * Create an instance of {@link GetPriceResponse }
     * 
     */
    public GetPriceResponse createGetPriceResponse() {
        return new GetPriceResponse();
    }

    /**
     * Create an instance of {@link PriceSOAP }
     * 
     */
    public PriceSOAP createPriceSOAP() {
        return new PriceSOAP();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link UserRequest }
     * 
     */
    public UserRequest createUserRequest() {
        return new UserRequest();
    }

    /**
     * Create an instance of {@link GetPriceRequest }
     * 
     */
    public GetPriceRequest createGetPriceRequest() {
        return new GetPriceRequest();
    }

    /**
     * Create an instance of {@link PriceRequest }
     * 
     */
    public PriceRequest createPriceRequest() {
        return new PriceRequest();
    }

    /**
     * Create an instance of {@link GetAccomodationResponse }
     * 
     */
    public GetAccomodationResponse createGetAccomodationResponse() {
        return new GetAccomodationResponse();
    }

    /**
     * Create an instance of {@link AccomodationSOAP }
     * 
     */
    public AccomodationSOAP createAccomodationSOAP() {
        return new AccomodationSOAP();
    }

    /**
     * Create an instance of {@link GetBonusServiceResponse }
     * 
     */
    public GetBonusServiceResponse createGetBonusServiceResponse() {
        return new GetBonusServiceResponse();
    }

    /**
     * Create an instance of {@link BonusServiceSOAP }
     * 
     */
    public BonusServiceSOAP createBonusServiceSOAP() {
        return new BonusServiceSOAP();
    }

    /**
     * Create an instance of {@link GetAccomodationTypeResponse }
     * 
     */
    public GetAccomodationTypeResponse createGetAccomodationTypeResponse() {
        return new GetAccomodationTypeResponse();
    }

    /**
     * Create an instance of {@link AccomodationTypeSOAP }
     * 
     */
    public AccomodationTypeSOAP createAccomodationTypeSOAP() {
        return new AccomodationTypeSOAP();
    }

    /**
     * Create an instance of {@link GetBonusServiceRequest }
     * 
     */
    public GetBonusServiceRequest createGetBonusServiceRequest() {
        return new GetBonusServiceRequest();
    }

    /**
     * Create an instance of {@link BonusServiceRequest }
     * 
     */
    public BonusServiceRequest createBonusServiceRequest() {
        return new BonusServiceRequest();
    }

    /**
     * Create an instance of {@link GetCommentResponse }
     * 
     */
    public GetCommentResponse createGetCommentResponse() {
        return new GetCommentResponse();
    }

    /**
     * Create an instance of {@link CommentSOAP }
     * 
     */
    public CommentSOAP createCommentSOAP() {
        return new CommentSOAP();
    }

    /**
     * Create an instance of {@link GetAccomodationRequest }
     * 
     */
    public GetAccomodationRequest createGetAccomodationRequest() {
        return new GetAccomodationRequest();
    }

    /**
     * Create an instance of {@link AccomodationRequest }
     * 
     */
    public AccomodationRequest createAccomodationRequest() {
        return new AccomodationRequest();
    }

    /**
     * Create an instance of {@link GetReservationResponse }
     * 
     */
    public GetReservationResponse createGetReservationResponse() {
        return new GetReservationResponse();
    }

    /**
     * Create an instance of {@link ReservationSOAP }
     * 
     */
    public ReservationSOAP createReservationSOAP() {
        return new ReservationSOAP();
    }

    /**
     * Create an instance of {@link GetAccomodationAgentRequest }
     * 
     */
    public GetAccomodationAgentRequest createGetAccomodationAgentRequest() {
        return new GetAccomodationAgentRequest();
    }

    /**
     * Create an instance of {@link AccomodationAgentRequest }
     * 
     */
    public AccomodationAgentRequest createAccomodationAgentRequest() {
        return new AccomodationAgentRequest();
    }

}
