
package xmlweb.agent.soap.reservation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationPort", targetNamespace = "http://xmlweb/projekat/entities/soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationPort {


    /**
     * 
     * @param getReservationRequest
     * @return
     *     returns xmlweb.agent.soap.reservation.GetReservationResponse
     */
    @WebMethod
    @WebResult(name = "getReservationResponse", targetNamespace = "http://xmlweb/projekat/soap/models", partName = "getReservationResponse")
    public GetReservationResponse getReservation(
        @WebParam(name = "getReservationRequest", targetNamespace = "http://xmlweb/projekat/soap/models", partName = "getReservationRequest")
        GetReservationRequest getReservationRequest);

}
