
package xmlweb.agent.soap.reservation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReservationPortService", targetNamespace = "http://xmlweb/projekat/entities/soap", wsdlLocation = "http://localhost:8089/booking/ws/reservation.wsdl")
public class ReservationPortService
    extends Service
{

    private final static URL RESERVATIONPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVATIONPORTSERVICE_EXCEPTION;
    private final static QName RESERVATIONPORTSERVICE_QNAME = new QName("http://xmlweb/projekat/entities/soap", "ReservationPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/booking/ws/reservation.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATIONPORTSERVICE_WSDL_LOCATION = url;
        RESERVATIONPORTSERVICE_EXCEPTION = e;
    }

    public ReservationPortService() {
        super(__getWsdlLocation(), RESERVATIONPORTSERVICE_QNAME);
    }

    public ReservationPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONPORTSERVICE_QNAME, features);
    }

    public ReservationPortService(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONPORTSERVICE_QNAME);
    }

    public ReservationPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONPORTSERVICE_QNAME, features);
    }

    public ReservationPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReservationPort
     */
    @WebEndpoint(name = "ReservationPortSoap11")
    public ReservationPort getReservationPortSoap11() {
        return super.getPort(new QName("http://xmlweb/projekat/entities/soap", "ReservationPortSoap11"), ReservationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservationPort
     */
    @WebEndpoint(name = "ReservationPortSoap11")
    public ReservationPort getReservationPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlweb/projekat/entities/soap", "ReservationPortSoap11"), ReservationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONPORTSERVICE_EXCEPTION!= null) {
            throw RESERVATIONPORTSERVICE_EXCEPTION;
        }
        return RESERVATIONPORTSERVICE_WSDL_LOCATION;
    }

}
