//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.24 at 12:00:44 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlweb/projekat/soap/services/realised_reservation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xmlweb.agent.soap.services.realised_reservation;
