//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 12:14:37 AM CEST 
//


package xmlweb.agent.soap.models.accomodation_type;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlweb.projekat.soap.models.accomodation_type package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlweb.projekat.soap.models.accomodation_type
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAccomodationTypeResponse }
     * 
     */
    public GetAccomodationTypeResponse createGetAccomodationTypeResponse() {
        return new GetAccomodationTypeResponse();
    }

    /**
     * Create an instance of {@link AccomodationTypeSOAP }
     * 
     */
    public AccomodationTypeSOAP createAccomodationTypeSOAP() {
        return new AccomodationTypeSOAP();
    }

    /**
     * Create an instance of {@link GetAccomodationTypeRequest }
     * 
     */
    public GetAccomodationTypeRequest createGetAccomodationTypeRequest() {
        return new GetAccomodationTypeRequest();
    }

    /**
     * Create an instance of {@link AccomodationTypeRequest }
     * 
     */
    public AccomodationTypeRequest createAccomodationTypeRequest() {
        return new AccomodationTypeRequest();
    }

}
