//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.24 at 09:55:26 AM CEST 
//


package xmlweb.projekat.soap.services.new_accomodation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlweb.projekat.soap.services.new_accomodation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlweb.projekat.soap.services.new_accomodation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetNewAccomodationResponse }
     * 
     */
    public GetNewAccomodationResponse createGetNewAccomodationResponse() {
        return new GetNewAccomodationResponse();
    }

    /**
     * Create an instance of {@link NewAccomodationSOAP }
     * 
     */
    public NewAccomodationSOAP createNewAccomodationSOAP() {
        return new NewAccomodationSOAP();
    }

    /**
     * Create an instance of {@link GetAccomodationRequest }
     * 
     */
    public GetAccomodationRequest createGetAccomodationRequest() {
        return new GetAccomodationRequest();
    }

    /**
     * Create an instance of {@link NewAccomodationRequest }
     * 
     */
    public NewAccomodationRequest createNewAccomodationRequest() {
        return new NewAccomodationRequest();
    }

}
