//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 01:54:52 PM CEST 
//


package xmlweb.projekat.soap.services.reserve_accomodation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reserve_accomodation" type="{http://xmlweb/projekat/soap/services/reserve_accomodation}ReserveAccomodationSOAP"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reserveAccomodation"
})
@XmlRootElement(name = "getReserveAccomodationResponse")
public class GetReserveAccomodationResponse {

    @XmlElement(name = "reserve_accomodation", required = true)
    protected ReserveAccomodationSOAP reserveAccomodation;

    /**
     * Gets the value of the reserveAccomodation property.
     * 
     * @return
     *     possible object is
     *     {@link ReserveAccomodationSOAP }
     *     
     */
    public ReserveAccomodationSOAP getReserveAccomodation() {
        return reserveAccomodation;
    }

    /**
     * Sets the value of the reserveAccomodation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReserveAccomodationSOAP }
     *     
     */
    public void setReserveAccomodation(ReserveAccomodationSOAP value) {
        this.reserveAccomodation = value;
    }

}
