//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 01:54:52 PM CEST 
//


package xmlweb.projekat.soap.services.reserve_accomodation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReserveAccomodationSOAP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReserveAccomodationSOAP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reserve_accomodation_response" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReserveAccomodationSOAP", propOrder = {
    "reserveAccomodationResponse"
})
public class ReserveAccomodationSOAP {

    @XmlElement(name = "reserve_accomodation_response")
    protected boolean reserveAccomodationResponse;

    /**
     * Gets the value of the reserveAccomodationResponse property.
     * 
     */
    public boolean isReserveAccomodationResponse() {
        return reserveAccomodationResponse;
    }

    /**
     * Sets the value of the reserveAccomodationResponse property.
     * 
     */
    public void setReserveAccomodationResponse(boolean value) {
        this.reserveAccomodationResponse = value;
    }

}
